### ISSUE TITLE
Bug in smalltalk learn page (profStef) - 22/24 Reflexion

### ISSUE THREAD

**Issue by mandorman** [amber-smalltalk/amber-website#12]
Dear Nicolas,

I performed the successfully the nice (and quick) introduction into smalltalk via the web. It works perfectly, but I got a error on issue 22 (Reflexion) when I try to compile a new method  on the fly.

```
     |newMethod|
    newMethod := Compiler new load: 'goToNextLesson ProfStef next.' forClass: ProfStef.
     ProfStef class addCompiledMethod: newMethod
     "Wow! I can't wait to use my new method!"
     ProfStef goToNextLesson.
```

So, when I execute:
   **newMethod := Compiler new load: 'goToNextLesson ProfStef next.' forClass: ProfStef.**, I got this error : 
   _a Compiler does not understand #load:forClass:_

Cheers,

**Comment by jan-tomsa** [comment]
ProfStef is already fixed in current version:
https://github.com/amber-smalltalk/amber-examples/blob/d7f9a9993739dcd3bd49eedef9a464a381ebbfc9/trysmalltalk/st/TrySmalltalk.st

The bug was fixed in
https://github.com/amber-smalltalk/amber-examples/commit/6cc631062652b6571385ac2a740c40ed7190444b
(2014-05-31)

so now it would be good to deploy fixed version of tutorial to the web.
