### ISSUE TITLE
Delete master branch

### ISSUE THREAD

**Issue by hhzl** [amber-smalltalk/amber-website#23]
Suggestion by Bert Freudenberg on the ML.

The branch used in this repository is the gh-pages branch.
The master branch has not been updated for a long time.
Having the master branch around is not necessary.
## Choose default branch

![choosing-the-github-default-branch](https://cloud.githubusercontent.com/assets/1112023/5838170/4c81e4b6-a17d-11e4-91cc-588aef27c155.png)
## Delete master branch

![delete-master-branch](https://cloud.githubusercontent.com/assets/1112023/5838183/61ef4d66-a17d-11e4-9242-e15625df1afa.png)

**Comment by hhzl** [comment]
gh-pages set as default branch

**Comment by hhzl** [comment]
@philippeback , @tomrake Any objections if I delete the master branch. We do not need it.

**Comment by tomrake** [comment]
I have examined the repository and branches in its current state today. Removing the master branch is unusual which is why I am going into this level of analysis.
1. The current master branch is OLD - last commit was on November 11, 2013, gh-pages branch has been currently updated.
2. The current master branch has FEWER COMMITS, only 6 while the gh-pages branch has perhaps 20 commits or more.
3. The current master does NOT HAVE a CNAME file to redirect the domain, the gh-pages branch has that.
4. The website is being hosted as a "project site" from amber-website. A "Project Site" and is hosted from the gh-pages branch. The possible alternative we have is to host an "Organization site" to host such a site we would need a repo named amber-smalltalk.github.io, in this case master will be served for a website, we have no such repo.

The master branch is OLD, has FEWER COMMITS, HAS NO DOMAIN related records and is not being served. The master branch can be removed or deleted without affecting the live pages of the website.

**Comment by mkroehnert** [comment]
No objections from my side.
The gh-pages is the only branch used to create the website.

One possible alternative would be to make GitHub use the master branch
instead of gh-pages, merge everything from gh-pages into master and then
remove the gh-pages branch.
But I don't see any advantage of doing so.

**Comment by hhzl** [comment]
@tomrake , @mkroehnert  Thank you for this careful analysis and the confirmation that the master branch may indeed be deleted. It will make it easier for people to contribute to the web site development.

Now: where is the button to actually delete the master branch. I thought it was under `settings` but I did not see it there.

**Comment by ghost** [comment]
Probably no button. Must clone and git-fu (`git push origin :master` IIRC).

Hannes Hirzel wrote:

**Comment by mkroehnert** [comment]
@hhzl one of the Google results for "Github delete branch" leads to this GH help page (see bottom for deleting branches): https://help.github.com/articles/viewing-branches-in-your-repository/

**Comment by hhzl** [comment]
@mkroehnert  thank you

![amber-website-delete-master_2015-02-22](https://cloud.githubusercontent.com/assets/1112023/6317054/e4b55f4c-ba37-11e4-8119-da06b0886fee.png)

## DELETED master branch

Restore option is available
![amber-web-site-restore-branch-option-2015-02-22](https://cloud.githubusercontent.com/assets/1112023/6317060/fd667e36-ba37-11e4-84fb-bb1367d96e6a.png)
